name: Continuous Integration

on:
  pull_request:
    branches: [ main ]  # Only for PRs to main

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]  # Use only Node 18 for consistency
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Update browserslist database
        run: npx update-browserslist-db@latest
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test -- --coverage --ci --watchAll=false --passWithNoTests
        
      - name: Build project
        run: npm run build
        env:
          CI: false
          NODE_OPTIONS: --openssl-legacy-provider
